apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: your-flask-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: "mysql"  
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DB
              value: "mydb"
---
apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-svc
spec:
  selector:
    app: two-tier-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30090  
