apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: web-daemonset
  labels:
    app: static-site
spec:
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: web
          image: farhan9889/website-host-kubernetes:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  type: NodePort
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
